---
on:
  push:
    branches: [hostAliases]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Helm Chart
        run: |
          pwd
          helm package .
          mv ejbca-community-helm*tgz docs/
          ls -la docs
