---
on:
  push:
    branches: [hostAliases]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Helm Chart
        run: |
          pwd
          helm package .
          mv ejbca-community-helm*tgz docs/
          git config --global user.email "jan+githubaction@tomasek.cz"
          git config --global user.name "GA behalf of Jan Tomasek"
          git add -A
          git commit -a -m "Automatic build"
          ls -la docs

      - name: Push changes
        uses: ad-m/github-push-action@master
